Pieces = new Meteor.Collection(null);
Composers = new Meteor.Collection(null);

[
{_id: 'attwood', name: 'Thomas Attwood'},
{_id: 'bach', name: 'Johann Sebastian Bach'},
{_id: 'bach-amb-notebook', name: 'Notebook for Anna Magdalena Bach'},
{_id: 'beethoven', name: 'Ludwig van Beethoven'},
{_id: 'bartok', name: 'Bela Bartok'},
{_id: 'berens', name: 'Hermann Berens'},
{_id: 'beyer', name: 'Ferdinand Beyer'},
{_id: 'bolck', name: 'Oscar Bolck'},
{_id: 'burgmuller', name: 'Johann Friedrich Burgmuller'},
{_id: 'czerny', name: 'Carl Czerny'},
{_id: 'diabelli', name: 'Anton Diabelli'},
{_id: 'duvernoy', name: 'J. B. Duvernoy'},
{_id: 'goedicke', name: 'Alexander Goedicke'},
{_id: 'gurlitt', name: 'Cornelius Gurlitt'},
{_id: 'hainhofer', name: 'Philipp Hainhofer'},
{_id: 'hassler', name: 'Johann William Hassler'},
{_id: 'haydn', name: 'Franz Joseph Haydn'},
{_id: 'hofe', name: 'Joachim von der Hofe'},
{_id: 'hook', name: 'James Hook'},
{_id: 'horvath', name: 'Geza Horvath'},
{_id: 'jcbach', name: 'Johann Christian Bach'},
{_id: 'kabalevsky', name: 'Dmitri Kabalevsky'},
{_id: 'kohler', name: 'Louis Kohler'},
{_id: 'kunz', name: 'Konrad Kunz'},
{_id: 'leomozart', name: 'Leopold Mozart'},
{_id: 'praetorius', name: 'Micheal Praetorius'},
{_id: 'rameau', name: 'Jean-Philippe Rameau'},
{_id: 'ravel', name: 'Maurice Ravel'},
{_id: 'reichardt', name: 'Johann Friedrich Reichardt'},
{_id: 'reinagle', name: 'Alexander Reinagle'},
{_id: 'rousseau', name: 'Jean Jacques Rousseau'},
{_id: 'salutrinskaya', name: 'Tat\'iana Salutrinskaya'},
{_id: 'schein', name: 'Johann Hermann Schein'},
{_id: 'schytte', name: 'Ludwig Schytte'},
{_id: 'telemann', name: 'Georg Philipp Telemann'},
{_id: 'turk', name: 'Daniel Gottlob Turk'},
{_id: 'vogel', name: 'Moritz Vogel'},
{_id: 'wilton', name: 'C. H. Wilton'},

].forEach(function (composer) {
	Composers.insert(composer);
});

[
{composer: 'attwood', level: 0, title: 'Tuneful Dialogue', score: 'Attwood-TunefulDialogue.pdf'},

{composer: 'bach', level: 1, title: 'Minuet', score: 'Bach-Minuet.pdf'},
{composer: 'bach', level: 6, title: 'Minuet in F Major', score: 'Bach-Minuet-BWV-113.pdf'},
{composer: 'bach', level: 5, title: 'Prelude in C Major', score: 'Bach-Prelude-BWV-924.pdf'},
{composer: 'bach', level: 9, title: 'Prelude in D Major', score: 'Bach-Prelude-BWV-925.pdf'},
{composer: 'bach', level: 7, title: 'Prelude in D Minor', score: 'Bach-Prelude-BWV-926.pdf'},
{composer: 'bach', level: 5, title: 'Prelude in F Major', score: 'Bach-Prelude-BWV-927.pdf'},
{composer: 'bach', level: 9, title: 'Prelude in F Major', score: 'Bach-Prelude-BWV-928.pdf'},
{composer: 'bach', level: 8, title: 'Prelude in G Minor', score: 'Bach-Prelude-BWV-930.pdf'},
{composer: 'bach', level: 7, title: 'Prelude in C Major', score: 'Bach-Prelude-BWV-933.pdf'},
{composer: 'bach', level: 6, title: 'Prelude in C Minor', score: 'Bach-Prelude-BWV-934.pdf'},
{composer: 'bach', level: 7, title: 'Prelude in D Minor', score: 'Bach-Prelude-BWV-935.pdf'},
{composer: 'bach', level: 8, title: 'Prelude in D Major', score: 'Bach-Prelude-BWV-936.pdf'},
{composer: 'bach', level: 8, title: 'Prelude in E Major', score: 'Bach-Prelude-BWV-937.pdf'},
{composer: 'bach', level: 8, title: 'Prelude in E Minor', score: 'Bach-Prelude-BWV-938.pdf'},
{composer: 'bach', level: 4, title: 'Prelude in C Major', score: 'Bach-Prelude-BWV-939.pdf'},
{composer: 'bach', level: 7, title: 'Prelude in D Minor', score: 'Bach-Prelude-BWV-940.pdf'},
{composer: 'bach', level: 6, title: 'Prelude in E Minor', score: 'Bach-Prelude-BWV-941.pdf'},
{composer: 'bach', level: 8, title: 'Prelude in A Minor', score: 'Bach-Prelude-BWV-942.pdf'},
{composer: 'bach', level: 9, title: 'Prelude in C Major', score: 'Bach-Prelude-BWV-943.pdf'},
{composer: 'bach', level: 6, title: 'Prelude in C Minor', score: 'Bach-Prelude-BWV-999.pdf'},
{composer: 'bach', level: 10, title: 'Fugue in C Major', score: 'Bach-Fugue-BWV-952.pdf'},
{composer: 'bach', level: 9, title: 'Fugue in C Major', score: 'Bach-Fugue-BWV-953.pdf'},
{composer: 'bach', level: 10, title: 'Fugue in C Minor', score: 'Bach-Fugue-BWV-961.pdf'},
{composer: 'bach', level: 9, title: 'Small Prelude and Fugue in A Minor', score: 'Bach-SmallPrelude&Fugue-BWV-895.pdf'},
{composer: 'bach', level: 9, title: 'Small Prelude and Fugue in D Minor', score: 'Bach-SmallPrelude&Fugue-BWV-899.pdf'},
{composer: 'bach', level: 9, title: 'Small Prelude and Fugue in E Minor', score: 'Bach-SmallPrelude&Fugue-BWV-900.pdf'},
{composer: 'bach', level: 9, title: 'Small Prelude and Fugue in G Major', score: 'Bach-SmallPrelude&Fugue-BWV-902.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 1 in C Major', score: 'Bach-Invention1-BWV-772.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 2 in C Minor', score: 'Bach-Invention2-BWV-773.pdf'},
{composer: 'bach', level: 8, title: 'Invention No. 3 in D Major', score: 'Bach-Invention3-BWV-774.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 4 in D Minor', score: 'Bach-Invention4-BWV-775.pdf'},
{composer: 'bach', level: 8, title: 'Invention No. 5 in E-flat Major', score: 'Bach-Invention5-BWV-776.pdf'},
{composer: 'bach', level: 8, title: 'Invention No. 6 in E Major', score: 'Bach-Invention6-BWV-777.pdf'},
{composer: 'bach', level: 8, title: 'Invention No. 7 in E Minor', score: 'Bach-Invention7-BWV-778.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 8 in F Major', score: 'Bach-Invention8-BWV-779.pdf'},
{composer: 'bach', level: 8, title: 'Invention No. 9 in F Minor', score: 'Bach-Invention9-BWV-780.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 10 in G Major', score: 'Bach-Invention10-BWV-781.pdf'},
{composer: 'bach', level: 9, title: 'Invention No. 11 in G Minor', score: 'Bach-Invention11-BWV-782.pdf'},
{composer: 'bach', level: 9, title: 'Invention No. 12 in A Major', score: 'Bach-Invention12-BWV-783.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 13 in A Minor', score: 'Bach-Invention13-BWV-784.pdf'},
{composer: 'bach', level: 7, title: 'Invention No. 14 in B-flat Major', score: 'Bach-Invention14-BWV-785.pdf'},
{composer: 'bach', level: 9, title: 'Invention No. 15 in B Minor', score: 'Bach-Invention15-BWV-786.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 1 in  C Major', score: 'Bach-Sinfonia1-BWV-787.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 2 in  C Minor', score: 'Bach-Sinfonia2-BWV-788.pdf'},
{composer: 'bach', level: 9, title: 'Sinfonia No. 3 in  D Major', score: 'Bach-Sinfonia3-BWV-789.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 4 in  D Minor', score: 'Bach-Sinfonia4-BWV-790.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 5 in  E-flat Major', score: 'Bach-Sinfonia5-BWV-791.pdf'},
{composer: 'bach', level: 9, title: 'Sinfonia No. 6 in  E Major', score: 'Bach-Sinfonia6-BWV-792.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 7 in  E Minor', score: 'Bach-Sinfonia7-BWV-793.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 8 in  F Major', score: 'Bach-Sinfonia8-BWV-794.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 9 in  F Minor', score: 'Bach-Sinfonia9-BWV-795.pdf'},
{composer: 'bach', level: 9, title: 'Sinfonia No. 10 in G Major', score: 'Bach-Sinfonia10-BWV-796.pdf'},
{composer: 'bach', level: 9, title: 'Sinfonia No. 11 in G Minor', score: 'Bach-Sinfonia11-BWV-797.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 12 in A Major', score: 'Bach-Sinfonia12-BWV-798.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 13 in A Minor', score: 'Bach-Sinfonia13-BWV-799.pdf'},
{composer: 'bach', level: 10, title: 'Sinfonia No. 14 in B-flat Major', score: 'Bach-Sinfonia14-BWV-800.pdf'},
{composer: 'bach', level: 9, title: 'Sinfonia No. 15 in B Minor', score: 'Bach-Sinfonia15-BWV-801.pdf'},

{composer: 'bach-amb-notebook', level: 4, title: 'Gavotte in F Major', score: 'Bach-Gavotte-Anh-131.pdf'},
{composer: 'bach-amb-notebook', level: 4, title: 'Marche in D Major', score: 'Bach-Marche-Anh-122.pdf'},
{composer: 'bach-amb-notebook', level: 6, title: 'Marche in G Major', score: 'Bach-Marche-Anh-124.pdf'},
{composer: 'bach-amb-notebook', level: 7, title: 'Marche E-flat Major', score: 'Bach-Marche-Anh-127.pdf'},
{composer: 'bach-amb-notebook', level: 4, title: 'Minuet in G Major', score: 'Bach-Minuet-Anh-114.pdf'},
{composer: 'bach-amb-notebook', level: 4, title: 'Minuet in G Minor', score: 'Bach-Minuet-Anh-115.pdf'},
{composer: 'bach-amb-notebook', level: 4, title: 'Minuet in G Major', score: 'Bach-Minuet-Anh-116.pdf'},
{composer: 'bach-amb-notebook', level: 6, title: 'Minuet in B-flat Major', score: 'Bach-Minuet-Anh-118.pdf'},
{composer: 'bach-amb-notebook', level: 5, title: 'Minuet in A Minor', score: 'Bach-Minuet-Anh-120.pdf'},
{composer: 'bach-amb-notebook', level: 5, title: 'Minuet in C Minor', score: 'Bach-Minuet-Anh-121.pdf'},
{composer: 'bach-amb-notebook', level: 4, title: 'Minuet in D Minor', score: 'Bach-Minuet-Anh-132.pdf'},
{composer: 'bach-amb-notebook', level: 4, title: 'Musette in D Major', score: 'Bach-Musette-Anh-126.pdf'},
{composer: 'bach-amb-notebook', level: 7, title: 'Polonaise in F Major', score: 'Bach-Polonaise-Anh-117.pdf'},
{composer: 'bach-amb-notebook', level: 6, title: 'Polonaise in G Minor', score: 'Bach-Polonaise-Anh-119.pdf'},
{composer: 'bach-amb-notebook', level: 7, title: 'Polonaise in G Minor', score: 'Bach-Polonaise-Anh-123.pdf'},
{composer: 'bach-amb-notebook', level: 7, title: 'Polonaise in G Minor', score: 'Bach-Polonaise-Anh-125.pdf'},
{composer: 'bach-amb-notebook', level: 7, title: 'Polonaise in D Minor', score: 'Bach-Polonaise-Anh-128.pdf'},
{composer: 'bach-amb-notebook', level: 7, title: 'Polonaise in G Major', score: 'Bach-Polonaise-Anh-130.pdf'},

{composer: 'bartok', level: 0, title: 'Folk Dance', score: 'Bartok-FolkDance.pdf'},
{composer: 'bartok', level: 0, title: 'Little Invention', score: 'Bartok-LittleInvention.pdf'},
{composer: 'bartok', level: 0, title: 'Walking', score: 'Bartok-Walking.pdf'},
{composer: 'bartok', level: 1, title: 'Folk Dance', score: 'Bartok-FolkDance2.pdf'},
{composer: 'bartok', level: 1, title: 'Hungarian Folk Song', score: 'Bartok-HungarianFolkSong.pdf'},
{composer: 'bartok', level: 8, title: 'Three Hungarian Songs', score: 'Bartok-ThreeHungarianSongs-Sz35.pdf'},
{composer: 'bartok', level: 8, title: 'Bagatelle No. 1', score: 'Bartok-BagatelleNo1-Op6-Sz38.pdf'},
{composer: 'bartok', level: 10, title: 'Bagatelle No. 2', score: 'Bartok-BagatelleNo2-Op6-Sz38.pdf'},
{composer: 'bartok', level: 7, title: 'Bagatelle No. 3', score: 'Bartok-BagatelleNo3-Op6-Sz38.pdf'},
{composer: 'bartok', level: 6, title: 'Bagatelle No. 4', score: 'Bartok-BagatelleNo4-Op6-Sz38.pdf'},
{composer: 'bartok', level: 9, title: 'Bagatelle No. 5', score: 'Bartok-BagatelleNo5-Op6-Sz38.pdf'},
{composer: 'bartok', level: 7, title: 'Bagatelle No. 6', score: 'Bartok-BagatelleNo6-Op6-Sz38.pdf'},
{composer: 'bartok', level: 11, title: 'Bagatelle No. 7', score: 'Bartok-BagatelleNo7-Op6-Sz38.pdf'},
{composer: 'bartok', level: 10, title: 'Bagatelle No. 8', score: 'Bartok-BagatelleNo8-Op6-Sz38.pdf'},
{composer: 'bartok', level: 10, title: 'Bagatelle No. 9', score: 'Bartok-BagatelleNo9-Op6-Sz38.pdf'},
{composer: 'bartok', level: 11, title: 'Bagatelle No. 10', score: 'Bartok-BagatelleNo10-Op6-Sz38.pdf'},
{composer: 'bartok', level: 10, title: 'Bagatelle No. 11', score: 'Bartok-BagatelleNo11-Op6-Sz38.pdf'},
{composer: 'bartok', level: 11, title: 'Bagatelle No. 12', score: 'Bartok-BagatelleNo12-Op6-Sz38.pdf'},
{composer: 'bartok', level: 7, title: 'Bagatelle No. 13', score: 'Bartok-BagatelleNo13-Op6-Sz38.pdf'},
{composer: 'bartok', level: 11, title: 'Bagatelle No. 14', score: 'Bartok-BagatelleNo14-Op6-Sz38.pdf'},
{composer: 'bartok', level: 7, title: 'Easy Pieces Intro', score: 'Bartok-EasyPiecesIntro-Sz39.pdf'},
{composer: 'bartok', level: 2, title: 'Easy Pieces No. 1', score: 'Bartok-EasyPiecesNo1-Sz39.pdf'},
{composer: 'bartok', level: 4, title: 'Easy Pieces No. 2', score: 'Bartok-EasyPiecesNo2-Sz39.pdf'},
{composer: 'bartok', level: 4, title: 'Easy Pieces No. 3', score: 'Bartok-EasyPiecesNo3-Sz39.pdf'},
{composer: 'bartok', level: 5, title: 'Easy Pieces No. 4', score: 'Bartok-EasyPiecesNo4-Sz39.pdf'},
{composer: 'bartok', level: 5, title: 'Easy Pieces No. 5', score: 'Bartok-EasyPiecesNo5-Sz39.pdf'},
{composer: 'bartok', level: 6, title: 'Easy Pieces No. 6', score: 'Bartok-EasyPiecesNo6-Sz39.pdf'},
{composer: 'bartok', level: 4, title: 'Easy Pieces No. 7', score: 'Bartok-EasyPiecesNo7-Sz39.pdf'},
{composer: 'bartok', level: 4, title: 'Easy Pieces No. 8', score: 'Bartok-EasyPiecesNo8-Sz39.pdf'},
{composer: 'bartok', level: 4, title: 'Easy Pieces No. 9', score: 'Bartok-EasyPiecesNo9-Sz39.pdf'},
{composer: 'bartok', level: 8, title: 'Easy Pieces No. 10', score: 'Bartok-EasyPiecesNo10-Sz39.pdf'},
{composer: 'bartok', level: 2, levelUpper: 8, title: 'Hungarian Folk Tunes', score: 'Bartok-HungarianFolkTunes-Sz42-V1.pdf'},
{composer: 'bartok', level: 3, levelUpper: 8, title: 'Slovakian Folk Tunes', score: 'Bartok-SlovakianFolkTunes-Sz42-V2.pdf'},
{composer: 'bartok', level: 10, title: 'Seven Sketches', score: 'Bartok-Sketches-Op9b-Sz44.pdf'},
{composer: 'bartok', level: 10, title: 'Allegro Barbaro', score: 'Bartok-AllegroBarbaro-Sz49.pdf'},
{composer: 'bartok', level: 1, levelUpper: 4, title: 'Piano Method', score: 'Bartok-PianoMethod-Sz53.pdf'},
{composer: 'bartok', level: 7, levelUpper: 8, title: 'Sonatina on Transylvanian Themes', score: 'Bartok-Sonatina-Sz55.pdf'},
{composer: 'bartok', level: 7, levelUpper: 10, title: 'Romanian Folk Dances', score: 'Bartok-RomanianFolkDances-Sz56.pdf'},
{composer: 'bartok', level: 10, title: 'Romanian Christmas Carols', score: 'Bartok-RomanianChristmasCarols-Sz57.pdf'},
{composer: 'bartok', level: 4, levelUpper: 9, title: 'Nine Little Pieces', score: 'Bartok-NineLittlePieces-Sz82.pdf'},
{composer: 'bartok', level: 10, title: 'Three Rondos', score: 'Bartok-ThreeRondos-Sz84.pdf'},
{composer: 'bartok', level: 1, levelUpper: 3, title: 'Mikrokosmos Book 1', score: 'Bartok-MikrokosmosBook1-Sz153.pdf'},
{composer: 'bartok', level: 3, levelUpper: 4, title: 'Mikrokosmos Book 2', score: 'Bartok-MikrokosmosBook2-Sz153.pdf'},
{composer: 'bartok', level: 4, levelUpper: 6, title: 'Mikrokosmos Book 3', score: 'Bartok-MikrokosmosBook3-Sz153.pdf'},
{composer: 'bartok', level: 6, levelUpper: 7, title: 'Mikrokosmos Book 4', score: 'Bartok-MikrokosmosBook4-Sz153.pdf'},
{composer: 'bartok', level: 7, levelUpper: 9, title: 'Mikrokosmos Book 5', score: 'Bartok-MikrokosmosBook5-Sz153.pdf'},
{composer: 'bartok', level: 9, levelUpper: 10, title: 'Mikrokosmos Book 6', score: 'Bartok-MikrokosmosBook6-Sz153.pdf'},

{composer: 'beethoven', level: 1, title: 'Village Dance', score: 'Beethoven-VillageDance.pdf'},
{composer: 'beethoven', level: 4, title: 'Seven Country Dances WoO 11', score: 'Beethoven-SevenCountryDances-WoO11.pdf'},
{composer: 'beethoven', level: 6, title: 'Three Contradances WoO 14', score: 'Beethoven-TwelveContradances-WoO14.pdf'},
{composer: 'beethoven', level: 5, title: 'Six Country Dances WoO 15', score: 'Beethoven-SixCountryDances-WoO15.pdf'},
{composer: 'beethoven', level: 3, levelUpper: 5, title: 'Twelve German Dances WoO 8', score: 'Beethoven-TwelveGermanDances-WoO8.pdf'},
{composer: 'beethoven', level: 3, levelUpper: 4, title: 'Twelve German Dances WoO 13', score: 'Beethoven-TwelveGermanDances-WoO13.pdf'},
{composer: 'beethoven', level: 2, title: 'Ecossaise WoO 23', score: 'Beethoven-Ecossaise-WoO23.pdf'},
{composer: 'beethoven', level: 7, title: 'Six Ecossaises WoO 83', score: 'Beethoven-SixEcossaises-WoO83.pdf'},
{composer: 'beethoven', level: 3, title: 'Ecossaise WoO 86', score: 'Beethoven-Ecossaise-WoO86.pdf'},
{composer: 'beethoven', level: 4, levelUpper: 8, title: 'Six Minuets WoO 10', score: 'Beethoven-SixMinuets-WoO10.pdf'},
{composer: 'beethoven', level: 8, title: 'Minuet And Trio WoO 82', score: 'Beethoven-MinuetAndTrio-WoO82.pdf'},
{composer: 'beethoven', level: 6, title: 'Waltz WoO 84', score: 'Beethoven-Waltz-WoO84.pdf'},
{composer: 'beethoven', level: 6, title: 'Waltz WoO 85', score: 'Beethoven-Waltz-WoO85.pdf'},
{composer: 'beethoven', level: 3, title: 'Sonatina No. 1 in G Major', score: 'Beethoven-SonatinaNo1-Anh5.pdf'},
{composer: 'beethoven', level: 4, title: 'Sonatina No. 2 in F Major', score: 'Beethoven-SonatinaNo2-Anh5.pdf'},
{composer: 'beethoven', level: 7, title: 'Sonatina WoO 51', score: 'Beethoven-Sonatina-WoO51.pdf'},
{composer: 'beethoven', level: 8, title: 'Bonn Sonata No. 1', score: 'Beethoven-BonnSonataNo1-WoO47.pdf'},
{composer: 'beethoven', level: 8, title: 'Bonn Sonata No. 2', score: 'Beethoven-BonnSonataNo2-WoO47.pdf'},
{composer: 'beethoven', level: 9, title: 'Bonn Sonata No. 3', score: 'Beethoven-BonnSonataNo3-WoO47.pdf'},
{composer: 'beethoven', level: 8, levelUpper: 10, title: 'Bagatelles Op. 33', score: 'Beethoven-Bagatelles-Op33.pdf'},
{composer: 'beethoven', level: 7, levelUpper: 9, title: 'Bagatelles Op. 119', score: 'Beethoven-Bagatelles-Op119.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 1', score: 'Beethoven-SonataNo1-Op2No1.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 5', score: 'Beethoven-SonataNo5-Op10No1.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 6', score: 'Beethoven-SonataNo6-Op10No2.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 8 (Pathetique)', score: 'Beethoven-SonataNo8-Op13.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 9', score: 'Beethoven-SonataNo9-Op14No1.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 10', score: 'Beethoven-SonataNo10-Op14No2.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 14 (Moonlight)', score: 'Beethoven-SonataNo14-Op27No2.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 19', score: 'Beethoven-SonataNo19-Op49No1.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 20', score: 'Beethoven-SonataNo20-Op49No2.pdf'},
{composer: 'beethoven', level: 10, title: 'Sonata No. 25', score: 'Beethoven-SonataNo25-Op79.pdf'},
{composer: 'beethoven', level: 7, title: 'Six Variations On A Swiss Song', score: 'Beethoven-SixVariationsOnASwissSong-WoO64.pdf'},
{composer: 'beethoven', level: 9, title: 'Six Variations On A Duet By Paisiello', score: 'Beethoven-SixVariationsOnADuetByPaisiello-WoO70.pdf'},
{composer: 'beethoven', level: 8, title: 'Six Variations', score: 'Beethoven-SixVariations-WoO77.pdf'},
{composer: 'beethoven', level: 8, title: 'Rondo In C Major', score: 'Beethoven-RondoInCMajor-Op51No1.pdf'},
{composer: 'beethoven', level: 11, title: 'Rondo In G Major', score: 'Beethoven-RondoInGMajor-Op51No2.pdf'},
{composer: 'beethoven', level: 6, title: 'Happy And Sad', score: 'Beethoven-HappyAndSad-WoO54.pdf'},
{composer: 'beethoven', level: 7, title: 'Fur Elise', score: 'Beethoven-FurElise-WoO59.pdf'},
{composer: 'beethoven', level: 7, title: 'Allemande', score: 'Beethoven-Allemande-WoO81.pdf'},

{composer: 'beyer', level: 0, title: 'A Short Story', score: 'Beyer-AShortStory.pdf'},
{composer: 'beyer', level: 0, title: 'Evening Song', score: 'Beyer-EveningSong.pdf'},
{composer: 'beyer', level: 0, title: 'Lyrical Piece', score: 'Beyer-LyricalPiece.pdf'},
{composer: 'beyer', level: 0, title: 'Melody', score: 'Beyer-Melody.pdf'},
{composer: 'beyer', level: 1, title: 'Round Dance', score: 'Beyer-RoundDance.pdf'},
{composer: 'beyer', level: 1, title: 'Two In One', score: 'Beyer-TwoInOne.pdf'},

{composer: 'bolck', level: 0, title: 'Five Note Sonatina', score: 'Bolck-FiveNoteSonatina.pdf'},

{composer: 'burgmuller', level: 7, title: 'Rondo all Turca', score: 'Burgmuller-RondoAllaTurca-Op68.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 1', score: 'Burgmuller-ProgressiveEtudeNo1-Op100.pdf'},
{composer: 'burgmuller', level: 3, title: 'Progressive Etude No. 2', score: 'Burgmuller-ProgressiveEtudeNo2-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 3', score: 'Burgmuller-ProgressiveEtudeNo3-Op100.pdf'},
{composer: 'burgmuller', level: 5, title: 'Progressive Etude No. 4', score: 'Burgmuller-ProgressiveEtudeNo4-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 5', score: 'Burgmuller-ProgressiveEtudeNo5-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 6', score: 'Burgmuller-ProgressiveEtudeNo6-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 7', score: 'Burgmuller-ProgressiveEtudeNo7-Op100.pdf'},
{composer: 'burgmuller', level: 5, title: 'Progressive Etude No. 8', score: 'Burgmuller-ProgressiveEtudeNo8-Op100.pdf'},
{composer: 'burgmuller', level: 7, title: 'Progressive Etude No. 9', score: 'Burgmuller-ProgressiveEtudeNo9-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 10', score: 'Burgmuller-ProgressiveEtudeNo10-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 11', score: 'Burgmuller-ProgressiveEtudeNo11-Op100.pdf'},
{composer: 'burgmuller', level: 7, title: 'Progressive Etude No. 12', score: 'Burgmuller-ProgressiveEtudeNo12-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 13', score: 'Burgmuller-ProgressiveEtudeNo13-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 14', score: 'Burgmuller-ProgressiveEtudeNo14-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 15', score: 'Burgmuller-ProgressiveEtudeNo15-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 16', score: 'Burgmuller-ProgressiveEtudeNo16-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 17', score: 'Burgmuller-ProgressiveEtudeNo17-Op100.pdf'},
{composer: 'burgmuller', level: 5, title: 'Progressive Etude No. 18', score: 'Burgmuller-ProgressiveEtudeNo18-Op100.pdf'},
{composer: 'burgmuller', level: 4, title: 'Progressive Etude No. 19', score: 'Burgmuller-ProgressiveEtudeNo19-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 20', score: 'Burgmuller-ProgressiveEtudeNo20-Op100.pdf'},
{composer: 'burgmuller', level: 5, title: 'Progressive Etude No. 21', score: 'Burgmuller-ProgressiveEtudeNo21-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 22', score: 'Burgmuller-ProgressiveEtudeNo22-Op100.pdf'},
{composer: 'burgmuller', level: 7, title: 'Progressive Etude No. 23', score: 'Burgmuller-ProgressiveEtudeNo23-Op100.pdf'},
{composer: 'burgmuller', level: 6, title: 'Progressive Etude No. 24', score: 'Burgmuller-ProgressiveEtudeNo24-Op100.pdf'},
{composer: 'burgmuller', level: 7, title: 'Progressive Etude No. 25', score: 'Burgmuller-ProgressiveEtudeNo25-Op100.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 1', score: 'Burgmuller-StudyNo1-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 2', score: 'Burgmuller-StudyNo2-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 3', score: 'Burgmuller-StudyNo3-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 4', score: 'Burgmuller-StudyNo4-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 5', score: 'Burgmuller-StudyNo5-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 6', score: 'Burgmuller-StudyNo6-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 7', score: 'Burgmuller-StudyNo7-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 8', score: 'Burgmuller-StudyNo8-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 9', score: 'Burgmuller-StudyNo9-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 10', score: 'Burgmuller-StudyNo10-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 11', score: 'Burgmuller-StudyNo11-Op105.pdf'},
{composer: 'burgmuller', level: 9, title: 'Study No. 12', score: 'Burgmuller-StudyNo12-Op105.pdf'},
{composer: 'burgmuller', level: 6, title: 'Characteristic Etude No. 1', score: 'Burgmuller-CharacteristicEtudeNo1-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 2', score: 'Burgmuller-CharacteristicEtudeNo2-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 3', score: 'Burgmuller-CharacteristicEtudeNo3-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 4', score: 'Burgmuller-CharacteristicEtudeNo4-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 5', score: 'Burgmuller-CharacteristicEtudeNo5-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 6', score: 'Burgmuller-CharacteristicEtudeNo6-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 7', score: 'Burgmuller-CharacteristicEtudeNo7-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 8', score: 'Burgmuller-CharacteristicEtudeNo8-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 9', score: 'Burgmuller-CharacteristicEtudeNo9-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 10', score: 'Burgmuller-CharacteristicEtudeNo10-Op109.pdf'},
{composer: 'burgmuller', level: 9, title: 'Characteristic Etude No. 11', score: 'Burgmuller-CharacteristicEtudeNo11-Op109.pdf'},
{composer: 'burgmuller', level: 9, title: 'Characteristic Etude No. 12', score: 'Burgmuller-CharacteristicEtudeNo12-Op109.pdf'},
{composer: 'burgmuller', level: 7, title: 'Characteristic Etude No. 13', score: 'Burgmuller-CharacteristicEtudeNo13-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 14', score: 'Burgmuller-CharacteristicEtudeNo14-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 15', score: 'Burgmuller-CharacteristicEtudeNo15-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 16', score: 'Burgmuller-CharacteristicEtudeNo16-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 17', score: 'Burgmuller-CharacteristicEtudeNo17-Op109.pdf'},
{composer: 'burgmuller', level: 8, title: 'Characteristic Etude No. 18', score: 'Burgmuller-CharacteristicEtudeNo18-Op109.pdf'},

{composer: 'czerny', level: 0, title: 'Dance', score: 'Czerny-Dance.pdf'},
{composer: 'czerny', level: 0, title: 'Going Downtown', score: 'Czerny-GoingDowntown.pdf'},
{composer: 'czerny', level: 0, title: 'Lullaby', score: 'Czerny-Lullaby.pdf'},
{composer: 'czerny', level: 0, title: 'March', score: 'Czerny-March.pdf'},
{composer: 'czerny', level: 0, title: 'Waltz', score: 'Czerny-Waltz.pdf'},
{composer: 'czerny', level: 1, title: 'Etude In C', score: 'Czerny-EtudeInC.pdf'},
{composer: 'czerny', level: 1, title: 'Etude In F', score: 'Czerny-EtudeInF.pdf'},
{composer: 'czerny', level: 1, title: 'Whistling Song', score: 'Czerny-WhistlingSong.pdf'},
{composer: 'czerny', level: 3, levelUpper: 7, title: '100 Progressive Etudes', score: 'Czerny-100ProgressiveEtudes-Op139.pdf'},
{composer: 'czerny', level: 8, levelUpper: 10, title: '125 Exercises For Passage Playing', score: 'Czerny-125ExercisesForPassagePlaying-Op261.pdf'},
{composer: 'czerny', level: 8, levelUpper: 10, title: 'School Of Velocity', score: 'Czerny-SchoolOfVelocity-Op299.pdf'},
{composer: 'czerny', level: 9, levelUpper: 10, title: '40 Daily Studies', score: 'Czerny-40DailyStudies-Op337.pdf'},
{composer: 'czerny', level: 2, levelUpper: 7, title: 'Practical Method For Beginners', score: 'Czerny-PracticalMethodForBeginners-Op599.pdf'},
{composer: 'czerny', level: 9, title: 'Preliminary School Of Finger Dexterity', score: 'Czerny-PreliminarySchoolOfFingerDexterity-Op636.pdf'},
{composer: 'czerny', level: 10, title: '24 Etudes For The Left Hand', score: 'Czerny-24EtudesForTheLeftHand-Op718.pdf'},
{composer: 'czerny', level: 10, title: 'The Art Of Finger Dexterity', score: 'Czerny-TheArtOfFingerDexterity-Op740.pdf'},
{composer: 'czerny', level: 2, levelUpper: 3, title: 'Five Finger Studies', score: 'Czerny-FiveFingerStudies-Op777.pdf'},
{composer: 'czerny', level: 10, title: '160 Eight Measure Exercises', score: 'Czerny-160EightMeasureExercises-Op821.pdf'},
{composer: 'czerny', level: 8, title: '30 Etudes In Technique', score: 'Czerny-30EtudesInTechnique-Op849.pdf'},

{composer: 'diabelli', level: 1, title: 'Bagatelle 2', score: 'Diabelli-Bagatelle2.pdf'},
{composer: 'diabelli', level: 1, title: 'Bagatelle', score: 'Diabelli-Bagatelle.pdf'},
{composer: 'diabelli', level: 1, title: 'Morning Song', score: 'Diabelli-MorningSong.pdf'},

{composer: 'duvernoy', level: 1, title: 'Song Without Words', score: 'Duvernoy-SongWithoutWords.pdf'},

{composer: 'goedicke', level: 0, title: 'Russian Dance', score: 'Goedicke-RussianDance.pdf'},

{composer: 'gurlitt', level: 0, title: 'Minuet', score: 'Gurlitt-Minuet.pdf'},
{composer: 'gurlitt', level: 0, title: 'Relay Race', score: 'Gurlitt-RelayRace.pdf'},
{composer: 'gurlitt', level: 0, title: 'Trumpet Tune', score: 'Gurlitt-TrumpetTune.pdf'},
{composer: 'gurlitt', level: 0, title: 'Waltz Op. 82 No. 18', score: 'Gurlitt-WaltzO82N18.pdf'},
{composer: 'gurlitt', level: 1, title: 'Invention Etude', score: 'Gurlitt-InventionEtude.pdf'},
{composer: 'gurlitt', level: 1, title: 'Sonatina In C', score: 'Gurlitt-SonatinaInC.pdf'},
{composer: 'gurlitt', level: 1, title: 'The Hunt', score: 'Gurlitt-TheHunt.pdf'},

{composer: 'hainhofer', level: 0, title: 'Echo Dance', score: 'Hainhofer-EchoDance.pdf'},

{composer: 'hassler', level: 1, title: 'Minuetto', score: 'Hassler-Minuetto.pdf'},

{composer: 'haydn', level: 1, title: 'Quadrille', score: 'Haydn-Quadrille.pdf'},

{composer: 'hofe', level: 0, title: 'Canario', score: 'Hofe-Canario.pdf'},

{composer: 'horvath', level: 0, title: 'Canzonetta', score: 'Horvath-Canzonetta.pdf'},

{composer: 'hook', level: 1, title: 'Minuet', score: 'Hook-Minuet.pdf'},

{composer: 'jcbach', level: 0, title: 'Minuet', score: 'ChristianBach-Minuet.pdf'},

{composer: 'kabalevsky', level: 0, title: 'Marching', score: 'Kabalevsky-Marching.pdf'},
{composer: 'kabalevsky', level: 0, title: 'Melody', score: 'Kabalevsky-Melody.pdf'},
{composer: 'kabalevsky', level: 0, title: 'Polka', score: 'Kabalevsky-Polka.pdf'},
{composer: 'kabalevsky', level: 0, title: 'Song Op. 39 No. 8', score: 'Kabalevsky-SongO39N8.pdf'},
{composer: 'kabalevsky', level: 1, title: 'A Game', score: 'Kabalevsky-AGame.pdf'},
{composer: 'kabalevsky', level: 1, title: 'Cradle Song', score: 'Kabalevsky-CradleSong.pdf'},
{composer: 'kabalevsky', level: 1, title: 'Dance', score: 'Kabalevsky-Dance.pdf'},
{composer: 'kabalevsky', level: 1, title: 'Funny Event', score: 'Kabalevsky-FunnyEvent.pdf'},
{composer: 'kabalevsky', level: 1, title: 'Little Scherzo', score: 'Kabalevsky-LittleScherzo.pdf'},
{composer: 'kabalevsky', level: 1, title: 'Scherzo', score: 'Kabalevsky-Scherzo.pdf'},

{composer: 'kohler', level: 0, title: 'A Pleasant Day', score: 'Kohler-APleasantDay.pdf'},
{composer: 'kohler', level: 0, title: 'Duet', score: 'Kohler-Duet.pdf'},
{composer: 'kohler', level: 0, title: 'Song Without Words', score: 'Kohler-SongWithoutWords.pdf'},
{composer: 'kohler', level: 0, title: 'Twinkle Twinkle Little Star', score: 'Kohler-TwinkleTwinkleLittleStar.pdf'},
{composer: 'kohler', level: 1, title: 'Carefree Stroll', score: 'Kohler-CarefreeStroll.pdf'},
{composer: 'kohler', level: 1, title: 'Etude In A Minor', score: 'Kohler-EtudeInAMinor.pdf'},

{composer: 'kunz', level: 0, title: 'A Serious Event', score: 'Kunz-ASeriousEvent.pdf'},

{composer: 'leomozart', level: 1, title: 'Minuet', score: 'Mozart-Minuet.pdf'},

{composer: 'praetorius', level: 0, title: 'Old German Dance', score: 'Praetorius-OldGermanDance.pdf'},

{composer: 'rameau', level: 1, title: 'Minuet', score: 'Rameau-Minuet.pdf'},

{composer: 'reichardt', level: 0, title: 'Duet In Contrary Motion', score: 'Reichardt-DuetInContraryMotion.pdf'},

{composer: 'reinagle', level: 0, title: 'Minuet', score: 'Reinagle-Minuet.pdf'},
{composer: 'reinagle', level: 0, title: 'Procession', score: 'Reinagle-Procession.pdf'},
{composer: 'reinagle', level: 0, title: 'Promenade', score: 'Reinagle-Promenade.pdf'},
{composer: 'reinagle', level: 0, title: 'Simple Song', score: 'Reinagle-SimpleSong.pdf'},
{composer: 'reinagle', level: 1, title: 'Minuet', score: 'Reinagle-Minuet2.pdf'},

{composer: 'rousseau', level: 1, title: 'The Village Prophet', score: 'Rousseau-TheVillageProphet.pdf'},

{composer: 'salutrinskaya', level: 1, title: 'The Shepard\'s Flute', score: 'Salutrinskaya-TheShepardsFlute.pdf'},

{composer: 'schein', level: 1, title: 'Allemande', score: 'Schein-Allemande.pdf'},

{composer: 'schytte', level: 1, title: 'Bagatelle', score: 'Schytte-Bagatelle.pdf'},
{composer: 'schytte', level: 1, title: 'In Church', score: 'Schytte-InChurch.pdf'},
{composer: 'schytte', level: 1, title: 'Melody For The Left Hand', score: 'Schytte-MelodyForTheLeftHand.pdf'},
{composer: 'schytte', level: 1, title: 'Minuetto', score: 'Schytte-Minuetto.pdf'},
{composer: 'schytte', level: 1, title: 'Scherzo', score: 'Schytte-Scherzo.pdf'},
{composer: 'schytte', level: 1, title: 'TheHarp', score: 'Schytte-TheHarp.pdf'},

{composer: 'telemann', level: 1, title: 'Gavotte', score: 'Telemann-Gavotte.pdf'},
{composer: 'telemann', level: 1, title: 'Minuet', score: 'Telemann-Minuet.pdf'},

{composer: 'turk', level: 0, title: 'Carefree', score: 'Turk-Carefree.pdf'},
{composer: 'turk', level: 0, title: 'Childrens Song', score: 'Turk-ChildrensSong.pdf'},
{composer: 'turk', level: 0, title: 'Lament', score: 'Turk-Lament.pdf'},
{composer: 'turk', level: 0, title: 'March In C', score: 'Turk-MarchInC.pdf'},
{composer: 'turk', level: 0, title: 'March In F', score: 'Turk-MarchInF.pdf'},
{composer: 'turk', level: 0, title: 'March In G 2', score: 'Turk-MarchInG2.pdf'},
{composer: 'turk', level: 0, title: 'March In G', score: 'Turk-MarchInG.pdf'},
{composer: 'turk', level: 0, title: 'Minuet', score: 'Turk-Minuet.pdf'},
{composer: 'turk', level: 1, title: 'Dance', score: 'Turk-Dance.pdf'},

{composer: 'vogel', level: 0, title: 'The Brave Knight', score: 'Vogel-TheBraveKnight.pdf'},

{composer: 'wilton', level: 0, title: 'Minuet', score: 'Wilton-Minuet.pdf'},
{composer: 'wilton', level: 0, title: 'Sonatina', score: 'Wilton-Sonatina.pdf'},

].forEach(function (piece) {
	Pieces.insert(piece);
});
